<section class="section">
    <div class="container">
        <div class="section-title">
            <h3>404 - Page Not Found</h3>
            <hr>
        </div>
        <?php if($msgErr): ?>
            <p><?= $msgErr; ?></p>
        <?php endif ?>
        <p>The page you are looking for no longer exists. Perhaps you can return back to the site's homepage and see if you can find what you are looking for. Or, you can try finding it with the information below.</p>
    </div>
</section>

