<section class="section">
    <div class="container">
    <?php if ($data): ?>
        <div class="section-title">
            <h3><?= $data->title; ?></h3>
            <hr>
        </div>
        <div class="row">
            <div class="col-6 p-5"><img src="<?= $data->imgUrl; ?>" alt=""></div>
            <div class="col-6 p-5"><p><?= $data->content; ?></p></div>
        </div>
    <?php else: ?>
        <div class="section-title">
            <h3>Article introuvable</h3>
            <hr>
        </div>
    <?php endif ?>
    </div>
</section>
