<section class="section">
    <div class="container">
        <?php foreach ($msgErr as $key => $value): if($key == 0): ?>
                <div class="section-title">
                    <h3><?= $value; ?></h3>
                    <hr>
                </div>
            <?php else: ?>
                <p><?= $value; ?></p>
            <?php endif ?>
        <?php endforeach ?>
    </div>
</section>

